### ISSUE TITLE
About custom datasets

### ISSUE THREAD

**Issue by caimaomao315** [MCG-NKU/E2FGVI#24]
Hello, very lucky to learn about your model.
I was able to successfully train the davis dataset, but there are some issues with defining the dataset.
There are 320 zip files in JPEGImages, each zip has ten photos.
There are 320 normal mask files in test_masks, each with ten mask photos.
test.json is the same as train.json.

But when we run our own file, the following error occurs：is invalid for input of size 11272192
******************************************************************************************************
Custom dataset directory：
dataset
——ballet
————JPEGImages
—————— xxx.zip
—————— .........
———test_masks
—————— xxx
————train.json
————test.json
*****************************************************************************************************
specific error：
Traceback (most recent call last):
  File "/home/u202080087/data/E2FGVI/train.py", line 84, in <module>
    mp.spawn(main_worker, nprocs=config['world_size'], args=(config, ))
  File "/home/u202080087/.conda/envs/e2f/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/u202080087/.conda/envs/e2f/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/u202080087/.conda/envs/e2f/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/u202080087/.conda/envs/e2f/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/u202080087/data/E2FGVI/train.py", line 64, in main_worker
    trainer.train()
  File "/home/u202080087/data/E2FGVI/core/trainer.py", line 288, in train
    self._train_epoch(pbar)
  File "/home/u202080087/data/E2FGVI/core/trainer.py", line 307, in _train_epoch
    pred_imgs, pred_flows = self.netG(masked_frames, l_t)
  File "/home/u202080087/.conda/envs/e2f/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/u202080087/.conda/envs/e2f/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/u202080087/.conda/envs/e2f/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/u202080087/data/E2FGVI/model/e2fgvi_hq.py", line 255, in forward
    trans_feat = self.transformer([trans_feat, fold_output_size])
  File "/home/u202080087/.conda/envs/e2f/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/u202080087/.conda/envs/e2f/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/u202080087/.conda/envs/e2f/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/u202080087/data/E2FGVI/model/modules/tfocal_transformer_hq.py", line 551, in forward
    attn_windows = self.attn(x_windows_all, mask_all=x_window_masks_all)
  File "/home/u202080087/.conda/envs/e2f/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/u202080087/data/E2FGVI/model/modules/tfocal_transformer_hq.py", line 252, in forward
    0] * self.window_size[1], C // self.num_heads), (q, k, v))
  File "/home/u202080087/data/E2FGVI/model/modules/tfocal_transformer_hq.py", line 248, in <lambda>
    lambda t: window_partition(t, self.window_size).view(
  File "/home/u202080087/data/E2FGVI/model/modules/tfocal_transformer_hq.py", line 132, in window_partition
    window_size[1], C)
RuntimeError: shape '[2, 8, 6, 5, 4, 9, 512]' is invalid for input of size 11272192
*****************************************************************************************************
Looking forward to your reply

**Comment by NK-CS-ZZL** [comment]
The size of frames causes this issue. Specifically, some operations in our model, such as the window separation in the focal attention, and downsampling in the encoder, constrain that the width must be divisible by 108 and the height must be divisible by 60. I suggest using cropping/resizing/padding to meet the constraint mentioned earlier.

**Comment by caimaomao315** [comment]
> 帧的大小会导致此问题。具体来说，我们模型中的一些操作，例如焦点注意力中的窗口分离和编码器中的下采样，限制宽度必须能被 108 整除，高度必须能被 60 整除。我建议使用裁剪/调整大小/填充来满足前面提到的约束。

Thanks, I understand. Is it still possible to fix video of any resolution by modifying the code part?

**Comment by NK-CS-ZZL** [comment]
I didn't fully understand what you meant. The 'code part' means the model architecture or the training code. In the training procedure, the resolution of frames isn't a decisive factor in the final performance, so cropping is a simple yet effective way to fulfill training. It may be laborious work if you want to adjust the entire model, and we can't guarantee the final performance.
我不太理解你的问题，这个“代码”是指模型结构还是训练代码？在训练中，图像分辨率对模型的最终结果影响不大，直接对图像裁剪训练就可以很便捷的满足训练需求。如果你想改变网络结构，这个工作可能比较复杂而且我们无法保证最终效果。

**Comment by caimaomao315** [comment]
> I didn't fully understand what you meant. The 'code part' means the model architecture or the training code. In the training procedure, the resolution of frames isn't a decisive factor in the final performance, so cropping is a simple yet effective way to fulfill training. It may be laborious work if you want to adjust the entire model, and we can't guarantee the final performance. 我不太理解你的问题，这个“代码”是指模型结构还是训练代码？在训练中，图像分辨率对模型的最终结果影响不大，直接对图像裁剪训练就可以很便捷的满足训练需求。如果你想改变网络结构，这个工作可能比较复杂而且我们无法保证最终效果。

好的 谢谢你的回复，另外我还想知道# Using this command to output a 720p video
python test.py --model e2fgvi_hq --video <video_path> --mask <mask_path>  --ckpt release_model/E2FGVI-HQ-CVPR22.pth --set_size --width 1280 --height 720   在test 我们是可以修复任意分辨率的视频序列吗

**Comment by Paper99** [comment]
如果使用e2fgvi_hq模型，那么就可以修复任意分辨率的视频序列。
--set_size是用来指定输入、输出分辨率大小的。如果不设置该句柄，那么e2fgvi_hq在测试阶段就直接输入并输出原始分辨率尺寸的视频。

**Comment by caimaomao315** [comment]
> 

好的谢谢大佬，我理解了之前的问题。可是我用hq训练 出的模型，出现了dis_ gen_ opt_三种，我尝试用这些模型去修复，都无法得到对应的结果。（使用作者提供的模型是可以修复视频的）
![image](https://user-images.githubusercontent.com/61854190/179675805-d1050fec-638c-46c9-909b-82249c9f23a7.png)

**Comment by caimaomao315** [comment]
> 1.使用gen_*.pth来进行修复。 2.是否使用youtube-vos进行训练？

感谢回复~，我在想是不是我训练的模型出了问题，我采用的数据集分辨率大小是432*240，但是每个视频文件夹里只有10张图像。

最后使用gen模型修复图像时显示：Animation was deleted without rendering anythin
This is most likely not intended
To prevent deletion, assign the Animation to a variable, e.g. `anim`, that exists until you have outputted the Animation using `plt.show()` or `anim.save()`.

另外修复时，我也有采用youtube-vos的数据集进行修复。

**Comment by caimaomao315** [comment]
> 1.使用gen_*.pth来进行修复。 2.是否使用youtube-vos进行训练？

您好~最近训练自己的数据集，有了以下不解之处~首先我的数据集是190个视频文件夹（50张一个视频文件），同理mask视频文件夹也一样，发现训练次数到5w次就会停止，在5w之前训练的gen模型都是可以顺利修复，而且效果不错，这证明了大佬的模型很优秀~，但我不能训练出6w及以上的模型（是我的视频帧的数量太少了吗），我尝试去看底层源码，并未找到解决办法~还请大佬指点一二

**Comment by Paper99** [comment]
您好，为什么训练到5w次会停止呢？能否详细描述下呢。

**Comment by caimaomao315** [comment]
> 您好，为什么训练到5w次会停止呢？能否详细描述下呢。

您好，我后面调整了lr": 1e-4参数，就可以继续训练~

**Comment by jiahui1688** [comment]
> > 您好，为什么训练到5w次会停止呢？能否详细描述下呢。
> 
> 您好，我后面调整了lr": 1e-4参数，就可以继续训练~

您好，请问是在5w次的时候，将学习率降低来避免训练崩溃的吗?还是其他的调整方法，方便分享出来吗？
